name: Release Drafter

on:
  push: 
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - uses: release-drafter/release-drafter@v5.15.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.vars.outputs.tag }}
          version: ${{ steps.vars.outputs.tag }}